version: '3'

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_DATABASE: pokemon-app
    volumes:
      - ./mongo:/data

